### ISSUE TITLE
Monoplotter digitization error - Pic2Map.py line 369, Event2 = QgsMouseEvent(.......)

### ISSUE THREAD

**Issue by bogibrynjar** [tproduit/pic2map#1]
Hi,

In version 3.0 of the plugin I get a Python error referencing that line in the pic2map.py code when trying to digitize on the monoplotter (using the test data).

I compared the code to version 2.3 and then uninstalled version 3.0 and installed 2.3 and that works. I'm not a programmer so not sure why it's giving an error but maybe something to check.

Cheers!

**Comment by tproduit** [comment]
Thank you for your issue. Do you have more details?
Did you try to digitize a point, line or polygon layer?
Did you click on "refresh layer" before?

**Comment by bogibrynjar** [comment]
No problem, it's a great plugin to have access to! As for details I was digitizing a line layer and "refresh layer" had no effect. As soon as trying to digitize with "Ctrl left-click" on the Monoplotter a Python error is thrown. I might add that I am using the Long Term Release of QGIS (v 2.8 64-bit).
