### ISSUE TITLE
qgis to swmm

### ISSUE THREAD

**Issue by trasto21** [tproduit/pic2map#19]
i'm trying to use "qgis to swmm"plugin with qgis 3.12.2 but there are any missing content in the downloaded file. i send notice to @m-kuhn (https://github.com/QGEP/QGEP/issues/571) and he give me your contact for an help. i need a procedure to import in swmm 5.1 from a qgis' shape file. i hope you can send me a solution.
thanks

Valerio

**Comment by tproduit** [comment]
Can we continue this discussion on the QGEP issue (QGEP/QGEP#571). This project is not related to QGEP SWMM.
