### ISSUE TITLE
Pic2Map setup

### ISSUE THREAD

**Issue by ermondo** [tproduit/pic2map#21]
Hello sir good day, 

I want to install pic2map tool to do orthorectification.
In the image I sent to you,URL:? can you send the information?
Is there a video or text file that clearly defines the download?

I can't load OpenGL, OpenGL accelerator, piexif python modules with OSGeo4W cmd can you help me please ?

my contact address: burokovic2@gmail.com

![pic2mapp](https://user-images.githubusercontent.com/65775388/82680190-976e5e00-9c54-11ea-8736-1d043ce61a68.PNG)

![1](https://user-images.githubusercontent.com/65775388/82680182-95a49a80-9c54-11ea-82c4-16ba2791fd10.PNG)

![2](https://user-images.githubusercontent.com/65775388/82680185-96d5c780-9c54-11ea-992a-7dabf220743c.PNG)

![3](https://user-images.githubusercontent.com/65775388/82680187-96d5c780-9c54-11ea-8a83-d2937ac8972b.PNG)

**Comment by frpin33** [comment]
Hello to you, 

if you read the installation part from the ReadMe on github, you can see that the pluggin require 3 diffrents libraries. To install them you need to find your OSGeo4W, usually the path is directly on C disk then go in the apps folder then in the python37 folder (C:\OSGeo4W64\apps\Python37). From this folder you can launch a command prompt. In the readme you will find the 3 required line to paste. It should launch an installation process.

![image](https://user-images.githubusercontent.com/22438251/82685406-244bf400-9c22-11ea-9bfe-170f619854a4.png)

**Comment by ermondo** [comment]
I have no experience with this, please have a chance to take a small video or picture? please ..

**Comment by frpin33** [comment]
I don't understand what is not clear. To open a command prompt you can write cmd in the window search bar and press enter it should open it. The path of the OSGeo4W64 is chosen when you install QGIS. By default it's in the C: disk drive, so if you change it when you did the installation you're the only one to who where it is on your PC. In the command prompt cd is change the current path of the commande line, you need to go in the python directory so when you call python it call the right one. The 3 line you need to paste after de cd call are : 

python -m pip install pyOpenGL
python -m pip install pyOpenGL_accelerate
python -m pip install piexif

You can do it one by one to make sure they are all install. Pip is a python library that facilitate the python libraries intallation. It's already install for you with OSGeo

**Comment by frpin33** [comment]
![image](https://user-images.githubusercontent.com/22438251/82688269-945c7900-9c26-11ea-9c80-c7bad3ec24b8.png)

**Comment by ermondo** [comment]
![33](https://user-images.githubusercontent.com/65775388/82688643-e66ec000-9c61-11ea-89ef-a6994322231d.jpg)

 
I tried to do what you said, but the problem I marked appears.

**Comment by frpin33** [comment]
the command is : cd C:\OSGeo4W64\apps\Python37

you forgot cd

**Comment by ermondo** [comment]
![2222](https://user-images.githubusercontent.com/65775388/82689602-6b0e0e00-9c63-11ea-930c-9974ab45076f.PNG)

![dddddd](https://user-images.githubusercontent.com/65775388/82689805-bde7c580-9c63-11ea-9c5c-e83da58662b4.PNG)

 
I understand the cd event :) but I get such a warning, am i on the right track ?

**Comment by frpin33** [comment]
Alright, I found an other simpler way to install the lib. 

Go to the OSGeo4W64 directory and open the batch file 

![image](https://user-images.githubusercontent.com/22438251/82690158-b1467b80-9c29-11ea-9eea-400a71758904.png)

write the command py3_env 

you should be able to launch the python -m pip command after
https://landscapearchaeology.org/2018/installing-python-packages-in-qgis-3-for-windows/

![image](https://user-images.githubusercontent.com/22438251/82690267-dfc45680-9c29-11ea-83cc-6b27010b86f1.png)

**Comment by ermondo** [comment]
![afafafa](https://user-images.githubusercontent.com/65775388/82690553-19668300-9c65-11ea-9a2e-62aba652dbe1.PNG)

Sir, I came across such a result, did I do it right?

**Comment by frpin33** [comment]
Yes, you can try to reinstall Pic2Map via QGIS

**Comment by ermondo** [comment]
I am trying right now,

![SSSS](https://user-images.githubusercontent.com/65775388/82690992-d953d000-9c65-11ea-9b7d-1249f70c07ba.PNG)

**Comment by frpin33** [comment]
https://gis.stackexchange.com/questions/161812/how-to-fix-qgis-plugins-crashing-with-nameerror-name-pyplugin-installer-is-n

This is what I found online, did you use the plugins manager to make the installation?

**Comment by ermondo** [comment]
I will delete the QGIS program and try again
