### ISSUE TITLE
Pic2Map measure 3D not working

### ISSUE THREAD

**Issue by mgallet1** [tproduit/pic2map#4]
Hello,
I'm using pic2map to reach my goals, which are measuring 3D distances in an oblique photograph.
I am able to fit the photo and DEM with the GCP method but once I'm in the monoplotter the measure 3D tool does nothing. I also have problems when running the orthorectification tool. It gives me an output with the right footprint but with wrong colors.
I have some python warning. I attached a screen shot with the python warning and the display of the raster orthorectified file.
![problem_pic2map](https://user-images.githubusercontent.com/35724299/35267374-5ba4929e-0026-11e8-8f93-60ebf4afbf85.PNG)

**Comment by tproduit** [comment]
After a click on `Measure 3D` the measurement window should open. To measure in 3D you have to use CTRL+click.
