### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by lisamcravey** [tproduit/pic2map#5]
Pic2Map won't install, as missing a module? 

![screen shot 2018-06-12 at 16 17 16](https://user-images.githubusercontent.com/40209398/41299981-92e2a81e-6e5c-11e8-89c7-65280a49e467.png)

**Comment by tproduit** [comment]
You have to install pyopengl http://pyopengl.sourceforge.net/

```
python -m pip install pyOpenGL
python -m pip install pyOpenGL_accelerate
```
Take care to use Python used by QGIS to install pyOpenGL

**Comment by ekulack** [comment]
Greetings, I'm having a similar issue when trying to install pyOpneGL and am receiving the following error.
![git](https://user-images.githubusercontent.com/51681025/59227470-e6290200-8b81-11e9-87bd-c5a4f985e5b0.JPG)

I'm using QGIS 3.4
Python 3.7
pip installer is 9.0.3
